### ISSUE TITLE
이벤트 메시지 출력 로그 관련

### ISSUE THREAD

**Issue by geowiz21** [yoondisk/MediaSAFE_HD_Basic#15]
플레이어 하단 이벤트 메시지 창에서 

플레이어 조작 시 출력되는 (Ready, Play, Waiting, Playing, pause)의 시간 값은

어떤 동작에 대한 시간인지 확인 부탁드립니다.

**Comment by kimdev1** [comment]
플레이어 하단의 이벤트 메시지에 출력되는 로그


Ready : 페이지 로딩 완료 시간 , 플레이어 조작 가능
Play : 플레이어 영상 재생 요청 시간
Waiting : 영상 재생 요청 후 대기 시작 시간
Playing : 영상 재생 시작 시간
pause : 플레이어 일시정지 버튼 클릭했을 때의 시간
