### ISSUE TITLE
영상 정보를 받아오는 주소 값 관련

### ISSUE THREAD

**Issue by SeonghunL** [yoondisk/MediaSAFE_HD_Basic#16]
html5_player에서 index 파일에 개인의 IP가 기입이 되어있는 것 같아 해당 IP 변수를
 localhost 또는 127.0.0.1로 바꾸는 것을 제안합니다. 

저장소에서 Pull 받을 때 수정해야하는 번거로움이 있어 IP 변수에
 localhost 또는 127.0.0.1로 교체해두면 다른 참여자들도 편리하게 이용할 수 있다고 생각합니다.

**Comment by kimdev1** [comment]
해당사항 수정완료하여 이슈 클로즈 합니다.
