### ISSUE TITLE
yoonagent 실행 관련

### ISSUE THREAD

**Issue by cashbook** [yoondisk/MediaSAFE_HD_Basic#17]
플레이어를 작동시키기 위해 모듈의 yoonagent를 실행함에 있어 터미널에서 직접 명령어를 통해 작동을 합니다.

그러나 종료할 때는 별다른 방법이 없어 강제종료를 하게됩니다. 별개의 모듈 off 기능은 따로 존재 하지 않아 보입니다.

플레이어 모듈의 on/off 기능에 대해 방식이 있는지 확인 부탁드립니다.

**Comment by kimdev1** [comment]
플레이어의 on/off 기능은 별도로 없으며, 다만 패키지 설치 시 서비스에 등록되도록 하였습니다.
PC 부팅시 자동으로 실행되며, 종료를 원하시면 프로세스를 종료시키면 됩니다.
