### ISSUE TITLE
브라우저 환경

### ISSUE THREAD

**Issue by land-hana** [yoondisk/MediaSAFE_HD_Basic#18]
개방형 OS마다 기본적으로 제공해주는 브라우저가 있습니다만, 그 외 리눅스, 데비안 환경에서 지원해주는 

브라우저를 터미널에서 별도로 설치 해 진행해보려 합니다.

크롬 이 외에 지원이 되는 브라우저들이 있는 지 확인 부탁드립니다.

**Comment by kimdev1** [comment]
현재 지원하는 브라우저는 개방형OS 공통으로 크롬, 파이어폭스, 웨일이며
구름OS의 구름브라우저, 티맥스OS의 togate에서도 지원합니다.
