### ISSUE TITLE
dump_player.php 파일 비교방법

### ISSUE THREAD

**Issue by leeinjae89** [yoondisk/MediaSAFE_HD_Basic#24]
dump_player.php에서는 vod_player.php와 차이점이 있다면 각각의 TC의 값들이 나오는 항목이 
다른 것으로 보입니다.

업데이트에서는 원본 파일, 암호화 파일 비교할 수 있다는 내용을 확인했습니다.
두 파일의 비교 방법이 정해진 방법이나 별도로 있는 지, 설명이 필요합니다.

**Comment by kimdev1** [comment]
dump_player에서는 재생 시 암/복호화 된 영상을 저장하게 됩니다.
플레이어 조작없이 마지막까지 재생이 되어야 순차적으로 파일이 저장됩니다.
재생이 끝나면 원본영상과 암/복호화 된 영상을 cmp명령어를 이용하여 비교합니다.
