### ISSUE TITLE
MediaSafe.deb 패키지 설치관련 이슈

### ISSUE THREAD

**Issue by geowiz21** [yoondisk/MediaSAFE_HD_Basic#26]
MediaSafe.deb 설치 시 구성요소 중

#### preinst (패키지 설치 전 실행 스크립트)
```
invoke-rc.d yoonauto stop
```

yoonauto 파일이 존재안할 시 리턴값으로 인한 버그발생을 방지하기 위해
아래와 같이 수정요청 드립니다.

```
if [ -f /etc/init.d/yoonauto ]
then
  invoke-rc.d yoonauto stop
fi
```

**Comment by kimdev1** [comment]
해당증상 발견 후 버그 수정 완료하여 이슈 클로즈 합니다.
