### ISSUE TITLE
php_player TC 관련

### ISSUE THREAD

**Issue by cashbook** [yoondisk/MediaSAFE_HD_Basic#30]
#### vod_player/live_player/dump_player의 페이지의 TC 값
> 관련이슈 #24 

TC1~3의 수치는 플레이어 재생시 연관이 있어보이나, 해당 값이 나오는
구체적인 설명이 필요합니다.

그리고 TC4, TC5도 관련해서 내용 부탁드립니다.

**Comment by kimdev1** [comment]
TC4는 재생 바나 영상 조작 시 자막 싱크의 소요시간을 나타낸 값입니다.
TC5는 #24 의 코멘트를 확인바랍니다.
